language: python
install: "pip install jsonschema==2.5.1 staticjinja==0.3.2 glob2==0.4.1"
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_65f4e18630cc_key -iv $encrypted_65f4e18630cc_iv -in travis-key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sha256sum ~/.ssh/id_rsa
script:
  - make check
  - make site
